import type { Capability } from './types';

export const BUILTIN_CAPABILITIES: Capability[] = [
  {
    id: 'core.file.read',
    domain: 'core',
    tools: [
      'readFile',
      'readMany',
      'findFiles',
      'searchFiles',
      'diffFiles',
      'listFiles',
      'listDirectory',
      'exists',
      'statFile',
      'hashFile',
      'getDirectorySize',
    ],
    inputTypes: ['text', 'code', 'json'],
    outputTypes: ['text', 'code', 'json'],
    riskLevel: 'read',
    plannerHints: '用于定位与读取工作区文本内容',
  },
  {
    id: 'core.file.write',
    domain: 'core',
    tools: [
      'writeFile',
      'createFile',
      'appendFile',
      'touch',
      'editFile',
      'patchFile',
      'applyPatch',
    ],
    inputTypes: ['text', 'code', 'json'],
    outputTypes: ['text', 'code', 'json'],
    riskLevel: 'write',
    plannerHints: '执行文本类文件创建与修改',
  },
  {
    id: 'core.file.manage',
    domain: 'core',
    tools: [
      'deleteFiles',
      'mkdir',
      'rename',
      'move',
      'copy',
      'copyPaths',
      'compress',
      'extract',
    ],
    inputTypes: ['binary', 'text'],
    outputTypes: ['binary', 'text'],
    riskLevel: 'destructive',
    requiresApproval: true,
    plannerHints: '目录级操作，建议先计划后执行',
  },
  {
    id: 'core.tool.load',
    domain: 'core',
    tools: ['loadTools'],
    inputTypes: ['text', 'json'],
    outputTypes: ['text', 'json'],
    riskLevel: 'read',
    plannerHints: '按需加载延后工具的 skill 并启用',
  },
  {
    id: 'core.workspace.tidy',
    domain: 'core',
    tools: ['applyTidyPlan'],
    inputTypes: ['json'],
    outputTypes: ['json'],
    riskLevel: 'destructive',
    requiresApproval: true,
    plannerHints:
      '批量移动/重命名工作区文件：必须先产出方案、经用户确认后再落盘',
  },
  {
    id: 'integration.web.search',
    domain: 'integration',
    tools: ['webSearch', 'fetchWebPage'],
    inputTypes: ['text'],
    outputTypes: ['text', 'json'],
    riskLevel: 'external',
    plannerHints: '访问互联网信息源',
  },
  {
    id: 'office.spreadsheet.readwrite',
    domain: 'office',
    tools: ['readSpreadsheet', 'writeSpreadsheet'],
    inputTypes: ['spreadsheet', 'json'],
    outputTypes: ['spreadsheet', 'json'],
    riskLevel: 'write',
    plannerHints: '处理 xlsx/xls/csv',
  },
  {
    id: 'office.document.read',
    domain: 'office',
    tools: ['readWord', 'readPresentation'],
    inputTypes: ['document', 'slides'],
    outputTypes: ['text', 'json'],
    riskLevel: 'read',
    plannerHints: '读取 Word/PPT 内容',
  },
  {
    id: 'office.document.write',
    domain: 'office',
    tools: [
      'writeWord',
      'writePresentation',
      'renderOfficeTemplate',
      'batchGenerateOfficeDocs',
    ],
    inputTypes: ['text', 'json'],
    outputTypes: ['document', 'slides'],
    riskLevel: 'write',
    plannerHints: '写入 Word/PPT 与模板渲染',
  },
  {
    id: 'coding.semantic.retrieve',
    domain: 'coding',
    tools: ['searchWorkspaceSemantic'],
    inputTypes: ['code', 'text'],
    outputTypes: ['text', 'json'],
    riskLevel: 'read',
    plannerHints: '语义检索工作区内容',
  },
  {
    id: 'coding.symbol.index',
    domain: 'coding',
    tools: ['searchSymbol', 'findReferences'],
    inputTypes: ['code', 'text'],
    outputTypes: ['text', 'json'],
    riskLevel: 'read',
    plannerHints: '符号级定义与引用查询，用于代码理解与定位',
  },
  {
    id: 'coding.impact.analysis',
    domain: 'coding',
    tools: ['analyzeImpact'],
    inputTypes: ['code', 'text'],
    outputTypes: ['json'],
    riskLevel: 'read',
    plannerHints: '改前影响分析：受影响文件数与调用点总数，用于判断改动范围',
  },
  {
    id: 'coding.ast.edit',
    domain: 'coding',
    tools: ['astEdit'],
    inputTypes: ['code', 'text'],
    outputTypes: ['text', 'json'],
    riskLevel: 'write',
    plannerHints: 'AST 级结构性编辑（rename/import/props 默认值），dryRun 默认仅返回 diff',
  },
  {
    id: 'coding.ast.inspect',
    domain: 'coding',
    tools: ['astCapabilities'],
    inputTypes: ['code', 'text'],
    outputTypes: ['json'],
    riskLevel: 'read',
    plannerHints: '查询某文件支持的 AST 操作，零加载',
  },
  {
    id: 'core.script',
    domain: 'core',
    tools: ['runScript'],
    inputTypes: ['text', 'json'],
    outputTypes: ['text', 'json'],
    riskLevel: 'write',
    // 脚本内可经 cottage.* 调用 agent 工具（含高危工具），每次执行前统一审批一次
    requiresApproval: true,
    plannerHints: '执行受控 JS 脚本（Worker 沙箱）',
  },
  {
    id: 'data.python',
    domain: 'coding',
    tools: ['runPython'],
    inputTypes: ['text', 'json'],
    outputTypes: ['text', 'json', 'image'],
    riskLevel: 'write',
    plannerHints: '在 Pyodide 中执行 Python 做数据分析与计算',
  },
  {
    id: 'integration.web.screenshot',
    domain: 'integration',
    tools: ['screenshotPage', 'captureBrowserPage'],
    inputTypes: ['text'],
    outputTypes: ['image'],
    riskLevel: 'external',
    plannerHints: '网页截图，经 Cottage Service 无头浏览器渲染后保存到工作区',
  },
  {
    id: 'integration.web.extract',
    domain: 'integration',
    tools: ['extractPage'],
    inputTypes: ['text'],
    outputTypes: ['text', 'json'],
    riskLevel: 'external',
    plannerHints: '结构化提取网页正文与元数据（类 Jina Reader）',
  },
  {
    id: 'integration.web.interact',
    domain: 'integration',
    tools: [
      'openBrowserPage',
      'clickElement',
      'typeText',
      'selectOption',
      'browserNavigate',
      'closeBrowserPage',
    ],
    inputTypes: ['text'],
    outputTypes: ['json'],
    riskLevel: 'external',
    requiresApproval: true,
    plannerHints: '会话式多步页面交互（点击/输入/选择/跳转），涉及外部站点操作，建议先计划后执行',
  },
  {
    id: 'office.pdf.read',
    domain: 'office',
    tools: ['readPdf'],
    inputTypes: ['binary', 'text'],
    outputTypes: ['text', 'json'],
    riskLevel: 'read',
    plannerHints: '提取 PDF 文本、页数与元数据',
  },
  {
    id: 'office.pdf.write',
    domain: 'office',
    tools: ['mergePdfs', 'splitPdf', 'createPdf'],
    inputTypes: ['binary', 'text'],
    outputTypes: ['binary'],
    riskLevel: 'write',
    plannerHints: '合并 / 拆分 / 从文本创建 PDF',
  },
  {
    id: 'chart.diagram',
    domain: 'chart',
    tools: ['renderMermaid'],
    inputTypes: ['text'],
    outputTypes: ['text'],
    riskLevel: 'write',
    plannerHints: '生成 Mermaid 示意图（流程图/架构图/时序图/思维导图），输出自包含 HTML',
  },
  {
    id: 'chart.datachart',
    domain: 'chart',
    tools: ['renderChart'],
    inputTypes: ['text', 'json'],
    outputTypes: ['text'],
    riskLevel: 'write',
    plannerHints: '生成 ECharts 数据图表（柱状/折线/饼图等），输出自包含 HTML',
  },
  {
    id: 'imagegen.text2image',
    domain: 'media',
    tools: ['generateImage'],
    inputTypes: ['text'],
    outputTypes: ['image'],
    riskLevel: 'external',
    plannerHints: '文生图：调用当前对话厂商的生图模型，结果保存到工作区并注入对话',
  },
  {
    id: 'imagegen.image2image',
    domain: 'media',
    tools: ['editImage'],
    inputTypes: ['image', 'text'],
    outputTypes: ['image'],
    riskLevel: 'external',
    plannerHints: '图生图/编辑：基于工作区已有图片按指令修改或生成变体',
  },
  {
    id: 'integration.deep.research',
    domain: 'integration',
    tools: ['saveResearchReport'],
    inputTypes: ['text', 'json'],
    outputTypes: ['text'],
    riskLevel: 'write',
    plannerHints: '将带引用来源的研究报告落盘为 Markdown，配合联网/PDF/图表能力完成深度研究',
  },
];
