<template>
  <div class="oc-home">
    <section class="oc-hero">
      <div class="oc-hero__grid" aria-hidden="true" />
      <div class="oc-wrap oc-hero__layout">
        <div class="oc-hero__content">
          <p class="oc-eyebrow">BROWSER-FIRST · LOCAL FOLDER AGENT</p>
          <h1><span>用浏览器和本地文件夹，</span><span>运行你的 Agent。</span></h1>
          <p class="oc-hero__lead">
            Open Cottage 是纯前端应用：浏览器提供界面和目录授权，本地文件夹作为工作区；配置模型后，即可完成读写文件、调用工具与生成内容等 Agent 任务。无需额外桌面客户端。
          </p>
          <div class="oc-hero__actions">
            <a class="oc-btn oc-btn--primary" href="/guide/first-setup">开始使用 <span>→</span></a>
            <a v-if="siteLinks.demo" class="oc-btn oc-btn--ghost" :href="siteLinks.demo" target="_blank" rel="noreferrer">打开官方 Demo <span>↗</span></a>
            <a v-if="siteLinks.source" class="oc-btn oc-btn--ghost" :href="siteLinks.source" target="_blank" rel="noreferrer">获取开源代码 <span>↗</span></a>
            <a class="oc-btn oc-btn--ghost" href="/guide/introduction">了解 Open Cottage</a>
          </div>
          <ul class="oc-proof" aria-label="产品特点">
            <li>纯前端，无需自建服务器</li>
            <li>本地文件夹作为工作区</li>
            <li>一切都在你的电脑里</li>
          </ul>
        </div>
        <div class="oc-workbench oc-workflow" aria-label="Open Cottage 工作方式">
          <p class="oc-workflow__label">最小组成</p>
          <div class="oc-workflow__steps">
            <article><span>01</span><div><strong>浏览器</strong><p>提供应用界面与本地目录访问权限</p></div></article>
            <article><span>02</span><div><strong>本地文件夹</strong><p>作为已有项目、资料与产出的工作区</p></div></article>
            <article><span>03</span><div><strong>模型与能力</strong><p>按任务启用，完成读写、生成与工具调用</p></div></article>
          </div>
          <div class="oc-workflow__outcome"><span>需要网页增强能力时</span><strong>按需连接 Cottage Service</strong><p>用于搜索、动态网页抓取与浏览器自动化</p></div>
        </div>
      </div>
    </section>

    <section class="oc-band oc-band--why"><div class="oc-wrap"><header class="oc-band__head"><p class="oc-kicker">数据安全</p><h2>没有服务器，也就没有「数据交给别人」的顾虑。</h2><p>Open Cottage 是纯前端应用，不需要、也不会替你搭建后端服务器。你的文件、对话记录与配置都留在自己的电脑和浏览器里；除了你主动配置与使用的模型服务，内容不会被发送到其他服务器。</p></header><div class="oc-why"><article class="oc-why__item"><span>01</span><h3>无需服务器</h3><p>整个应用在你的浏览器里运行，没有必须托管的后端，也就不存在服务器泄露或停服的问题。</p></article><article class="oc-why__item"><span>02</span><h3>文件不出你的电脑</h3><p>Agent 只读写你亲手授权的本地文件夹，成果直接落在原目录，不会上传到任何服务器。</p></article><article class="oc-why__item"><span>03</span><h3>对话与配置留在浏览器</h3><p>聊天记录、工作区配置保存在浏览器与本地工作区；API Key 只存你自己的浏览器，我们不代为保管。</p></article><article class="oc-why__item"><span>04</span><h3>模型由你选择</h3><p>调用模型时，内容由你配置的模型服务直接处理；是否使用、使用哪家，始终由你决定。</p></article></div><a class="oc-text-link" href="/guide/security">查看完整安全说明 <span>→</span></a></div></section>

    <section class="oc-band oc-band--scenes"><div class="oc-wrap"><header class="oc-band__head"><p class="oc-kicker">按需开启的能力</p><h2>能力服务于任务，不需要成为使用门槛。</h2><p>首次使用只需配置模型并打开工作区。需要时再选择对应能力；这里提供一份简要目录。</p></header><ul class="oc-capability-list"><li v-for="sc in scenes" :key="sc.href"><a :href="sc.href"><span class="oc-capability-list__icon">{{ sc.icon }}</span><span>{{ sc.title }}</span><small>{{ sc.tag }}</small><b aria-hidden="true">→</b></a></li></ul></div></section>

    <section class="oc-band oc-band--flow"><div class="oc-wrap"><header class="oc-band__head"><p class="oc-kicker">开始使用</p><h2>四步完成最小配置。</h2><p>官方 Demo 适合直接体验；需要高级用法时再用开源代码自行部署。需要搜索、动态网页或自动化时，再按需连接 <a href="/concepts/cottage-service-concepts">Cottage Service</a>。</p></header><div class="oc-flow"><article v-for="s in flow" :key="s.n" class="oc-flow__item"><span class="oc-flow__n">{{ s.n }}</span><h3>{{ s.t }}</h3><p>{{ s.d }}</p></article></div></div></section>

    <section class="oc-band oc-band--cta"><div class="oc-wrap oc-cta"><p class="oc-kicker">开始使用</p><h2>打开一个文件夹，<br />在原有目录中完成工作。</h2><p>配置模型后即可开始；生成、修改与确认都在同一个工作区完成。</p><div class="oc-hero__actions"><a class="oc-btn oc-btn--primary" href="/guide/first-setup">开始五分钟配置 <span>→</span></a><a v-if="siteLinks.demo" class="oc-btn oc-btn--ghost" :href="siteLinks.demo" target="_blank" rel="noreferrer">打开官方 Demo <span>↗</span></a><a v-if="siteLinks.source" class="oc-btn oc-btn--ghost" :href="siteLinks.source" target="_blank" rel="noreferrer">获取开源代码 <span>↗</span></a><a class="oc-btn oc-btn--ghost" href="/concepts/">了解核心概念</a></div></div></section>
  </div>
</template>

<script setup lang="ts">
import { siteLinks } from '../../site-links.mjs'

const flow = [{ n: '01', t: '打开应用', d: '使用官方 Demo，或运行自行部署的实例。' }, { n: '02', t: '选择本地文件夹', d: '授权浏览器访问已有项目或资料目录。' }, { n: '03', t: '配置模型与能力', d: '选择可用模型；只在需要时开启对应能力。' }, { n: '04', t: '开始任务', d: '说明目标、输出路径和边界，让结果直接落在工作区。' }]
const scenes = [{ icon: '✦', tag: '办公', title: 'Word / PPT / 表格', href: '/guide/use-office' }, { icon: '⌘', tag: '编码', title: '代码改造', href: '/guide/use-coding' }, { icon: '⌕', tag: '研究', title: '调研报告', href: '/guide/use-research' }, { icon: '↗', tag: '网页', title: '网页处理', href: '/guide/use-web' }, { icon: '▧', tag: 'PDF / 图表', title: 'PDF 与图表', href: '/guide/use-pdf-chart' }, { icon: '✓', tag: '计划', title: '计划模式', href: '/guide/spec' }]
</script>

<style scoped>
.oc-home { --oc-ink: var(--cottage-ink); --oc-muted: var(--cottage-ink-soft); color: var(--oc-ink); }
.oc-wrap { width: min(1120px, calc(100% - 40px)); margin: 0 auto; }
.oc-hero { position: relative; isolation: isolate; overflow: hidden; background: #132019; color: #f4f7f2; }
.oc-hero::before { position: absolute; z-index: -2; inset: 0; background: linear-gradient(90deg, rgba(17,19,18,.95) 0%, rgba(20,24,22,.87) 37%, rgba(27,32,29,.67) 67%, rgba(35,39,34,.44) 100%), linear-gradient(0deg, rgba(11,13,12,.48), transparent 55%), url('/hero-cottage-v2.png') center / cover no-repeat; content: ''; }
.oc-hero__grid { position: absolute; z-index: -1; inset: 0; opacity: .18; background-image: linear-gradient(rgba(222,239,222,.13) 1px, transparent 1px), linear-gradient(90deg, rgba(222,239,222,.13) 1px, transparent 1px); background-size: 42px 42px; mask-image: linear-gradient(90deg, #000 0%, transparent 78%); }
.oc-hero__layout { min-height: min(760px, calc(100vh - var(--vp-nav-height))); display: grid; grid-template-columns: .94fr 1.06fr; align-items: center; gap: 62px; padding: 100px 0 84px; }
.oc-eyebrow,.oc-kicker { margin: 0 0 16px; color: var(--oc-accent); font-size: .72rem; font-weight: 750; letter-spacing: .13em; }
.oc-eyebrow { color: #bbd4bf; }
.oc-hero h1 { margin: 0 0 22px; font-size: clamp(2.55rem, 4.3vw, 4.2rem); line-height: 1.1; letter-spacing: -.045em; font-weight: 680; }
.oc-hero__lead { max-width: 37rem; margin: 0 0 31px; color: rgba(244,247,242,.78); font-size: 1.03rem; line-height: 1.75; }
.oc-hero__actions { display: flex; flex-wrap: wrap; gap: 12px; }
.oc-btn { display: inline-flex; align-items: center; justify-content: center; gap: 12px; min-height: 45px; padding: 0 19px; border: 1px solid transparent; border-radius: 8px; color: inherit; font-size: .93rem; font-weight: 680; text-decoration: none; transition: transform .18s ease, background .18s ease; }.oc-btn:hover { transform: translateY(-2px); }.oc-btn--primary { background: #d7e5d6; color: #17321e; }.oc-btn--primary:hover { background: #fff; }.oc-btn--ghost { border-color: rgba(238,247,237,.32); background: rgba(255,255,255,.04); }.oc-btn--ghost:hover { background: rgba(255,255,255,.11); }
.oc-proof { display: flex; flex-wrap: wrap; gap: 16px; padding: 0; margin: 38px 0 0; list-style: none; color: rgba(244,247,242,.67); font-size: .8rem; }.oc-proof li::before { content: '✓'; color: #b7d9ba; margin-right: 7px; }
.oc-workbench { position: relative; border: 1px solid rgba(216,236,216,.2); border-radius: 12px; overflow: hidden; background: #f6f8f5; color: #26332a; box-shadow: 0 32px 80px rgba(0,0,0,.34); transform: rotate(1.2deg); }.oc-workbench__bar { display: flex; align-items: center; gap: 6px; height: 42px; padding: 0 13px; background: #e9eee9; border-bottom: 1px solid #d9e0d8; }.oc-workbench__bar > span { width: 8px; height: 8px; border-radius: 50%; background: #a8b5a8; }.oc-workbench__bar b { margin-left: 8px; font-size: .76rem; }.oc-workbench__bar em { margin-left: auto; padding: 3px 7px; border-radius: 99px; background: #dcebdd; color: #3e6948; font-size: .64rem; font-style: normal; }.oc-workbench__body { display: grid; grid-template-columns: 31% 1fr; min-height: 355px; }.oc-files { display: flex; flex-direction: column; gap: 11px; padding: 20px 13px; background: #eff3ef; border-right: 1px solid #dce3dc; color: #657066; font-size: .68rem; }.oc-files p,.oc-files strong { margin: 0; font-size: .62rem; letter-spacing: .07em; }.oc-files strong { color: #526154; }.oc-files span { padding: 5px 7px; }.oc-files .is-active { border-radius: 4px; background: #dbe8dc; color: #315f3b; }.oc-task { padding: 20px; }.oc-chat { display: flex; gap: 8px; align-items: flex-start; }.oc-chat i { display: grid; place-items: center; flex: 0 0 22px; width: 22px; height: 22px; border-radius: 50%; background: #355b3d; color: #fff; font-size: .62rem; font-style: normal; }.oc-chat p { margin: 3px 0 16px; font-size: .75rem; line-height: 1.5; }.oc-plan { padding: 11px; border: 1px solid #d7e2d8; border-radius: 6px; background: #fff; }.oc-plan small,.oc-change small { color: #748276; font-size: .62rem; }.oc-plan p { display: flex; align-items: center; gap: 6px; margin: 8px 0 0; font-size: .67rem; }.oc-plan b { display: grid; place-items: center; width: 15px; height: 15px; border-radius: 50%; background: #dcebdd; color: #35613e; font-size: .56rem; }.oc-plan mark { margin-left: auto; color: #4c8056; background: transparent; font-size: .58rem; }.oc-change { display: grid; grid-template-columns: 1fr auto; gap: 8px; align-items: center; padding: 11px; margin-top: 12px; border-left: 3px solid #6d9c72; background: #edf5ed; }.oc-change strong { display: block; margin-top: 3px; font-size: .66rem; }.oc-change > span { color: #4f7e58; font-family: var(--oc-mono); font-size: .62rem; }.oc-change button,.oc-review-card button { grid-column: 1 / -1; justify-self: start; padding: 0; border: 0; background: transparent; color: #376a42; font-size: .64rem; font-weight: 700; }.oc-done { margin-top: 13px; color: #4c8056; font-size: .65rem; }
.oc-hero__layout { grid-template-columns: 1.1fr .9fr; gap: 50px; }.oc-hero h1 { font-size: clamp(2.4rem, 4vw, 3.45rem); letter-spacing: -.055em; }.oc-hero h1 span { display: block; white-space: nowrap; }
.oc-workflow { display: block; padding: 34px; overflow: visible; border-color: rgba(248,250,246,.74); background: rgba(248,250,246,.86); backdrop-filter: blur(10px); color: #26332a; box-shadow: 0 24px 60px rgba(0,0,0,.2); transform: none; }.oc-workflow__label { margin: 0 0 27px; color: #56735c; font-family: var(--oc-mono); font-size: .66rem; font-weight: 700; letter-spacing: .13em; }.oc-workflow__steps { position: relative; display: grid; gap: 0; }.oc-workflow__steps::before { position: absolute; top: 17px; bottom: 17px; left: 13px; width: 1px; background: #cbd8cc; content: ''; }.oc-workflow__steps article { position: relative; display: grid; grid-template-columns: 27px 1fr; gap: 15px; padding: 0 0 25px; }.oc-workflow__steps article:last-child { padding-bottom: 10px; }.oc-workflow__steps span { z-index: 1; display: grid; place-items: center; width: 27px; height: 27px; border: 1px solid #aac3ad; border-radius: 50%; background: #e7f0e6; color: #406b48; font-family: var(--oc-mono); font-size: .55rem; font-weight: 700; }.oc-workflow__steps strong { display: block; margin: 3px 0 4px; font-size: 1rem; font-weight: 680; }.oc-workflow__steps p { margin: 0; color: #647066; font-size: .83rem; line-height: 1.5; }.oc-workflow__outcome { margin-top: 25px; padding: 18px; border: 1px solid rgba(212,224,212,.88); border-radius: 8px; background: rgba(237,244,235,.78); }.oc-workflow__outcome span { display: block; margin-bottom: 6px; color: #56735c; font-size: .67rem; font-weight: 700; letter-spacing: .08em; }.oc-workflow__outcome strong { display: block; font-size: 1.08rem; }.oc-workflow__outcome p { margin: 8px 0 0; color: #647066; font-size: .76rem; }
.oc-band { padding: 96px 0; }.oc-band--why,.oc-band--scenes { background: color-mix(in srgb, var(--oc-accent) 5%, var(--vp-c-bg)); }.oc-band--flow { background: linear-gradient(120deg, color-mix(in srgb, var(--oc-accent) 10%, var(--vp-c-bg)), var(--vp-c-bg) 48%); }.oc-band--cta { padding-bottom: 124px; }
.oc-band__head { margin-bottom: 43px; }.oc-band__head--wide {  }.oc-band__head h2,.oc-split__copy h2,.oc-cta h2 { margin: 0 0 12px; color: var(--vp-c-text-1); font-size: clamp(1.85rem,3vw,2.6rem); line-height: 1.22; letter-spacing: -.035em; font-weight: 680; }.oc-band__head p:not(.oc-kicker),.oc-split__copy > p:not(.oc-kicker),.oc-cta > p:not(.oc-kicker) { margin: 0; color: var(--vp-c-text-2); font-size: 1rem; line-height: 1.75; }
.oc-why { display: grid; grid-template-columns: repeat(4,1fr); gap: 18px; }.oc-why__item { padding: 20px 4px 0; border-top: 2px solid color-mix(in srgb,var(--oc-accent) 52%,transparent); }.oc-why__item > span { color: var(--oc-accent); font-family: var(--oc-mono); font-size: .7rem; }.oc-why__item h3 { margin: 18px 0 10px; font-size: 1.05rem; }.oc-why__item p,.oc-flow__item p { margin: 0; color: var(--vp-c-text-2); font-size: .92rem; line-height: 1.65; }
.oc-split { display: grid; grid-template-columns: .9fr 1.1fr; align-items: center; gap: 76px; }.oc-text-link { display: inline-block; margin-top: 21px; color: var(--oc-accent); font-size: .93rem; font-weight: 700; text-decoration: none; }.oc-text-link span { margin-left: 7px; }.oc-text-link:hover { text-decoration: underline; }.oc-review-card { border: 1px solid var(--oc-line); border-radius: 10px; overflow: hidden; background: var(--vp-c-bg-soft); box-shadow: 0 18px 42px rgba(31,42,33,.1); }.oc-review-card__head,.oc-review-card__foot { display: flex; justify-content: space-between; align-items: center; padding: 14px 17px; border-bottom: 1px solid var(--oc-line); font-size: .78rem; font-weight: 700; }.oc-review-card__head small,.oc-review-card__foot span { color: var(--vp-c-text-2); font-weight: 500; }.oc-diff { padding: 15px 17px; background: var(--vp-c-bg); font-family: var(--oc-mono); font-size: .77rem; }.oc-diff code { color: var(--vp-c-text-2); }.oc-diff p { margin: 10px 0 0; padding: 5px 8px; }.oc-diff .minus { background: rgba(194,84,70,.11); color: #a3463a; }.oc-diff .plus { background: rgba(72,132,82,.13); color: #3d7447; }.oc-review-card__foot { border: 0; }.oc-review-card button { justify-self: auto; color: var(--oc-accent); }
.oc-service-card__body { padding: 7px 18px; }.oc-service-card__body article { display: grid; grid-template-columns: 30px 1fr; gap: 12px; padding: 17px 0; border-bottom: 1px solid var(--oc-line); }.oc-service-card__body article:last-child { border-bottom: 0; }.oc-service-card__body b { display: grid; place-items: center; width: 26px; height: 26px; border-radius: 50%; background: var(--oc-soft); color: var(--oc-accent); font-family: var(--oc-mono); font-size: .63rem; }.oc-service-card__body strong { display: block; margin: 2px 0 4px; font-size: .94rem; }.oc-service-card__body p { margin: 0; color: var(--vp-c-text-2); font-size: .82rem; line-height: 1.45; }
.oc-flow { display: grid; grid-template-columns: repeat(4,1fr); gap: 17px; }.oc-flow__item { padding: 20px 18px; border: 1px solid var(--oc-line); border-radius: 8px; background: var(--vp-c-bg); }.oc-flow__n { display: block; margin-bottom: 37px; color: var(--oc-accent); font-family: var(--oc-mono); font-size: .7rem; font-weight: 700; }.oc-flow__item h3 { margin: 0 0 8px; font-size: 1.04rem; }
.oc-scenes { display: grid; grid-template-columns: repeat(3,1fr); border-top: 1px solid var(--oc-line); border-left: 1px solid var(--oc-line); }.oc-scene { min-height: 230px; padding: 23px; border-right: 1px solid var(--oc-line); border-bottom: 1px solid var(--oc-line); color: inherit; text-decoration: none; transition: background .18s ease, transform .18s ease; }.oc-scene:hover { background: color-mix(in srgb,var(--oc-accent) 8%,transparent); transform: translateY(-3px); }.oc-scene__icon { display: block; height: 27px; color: var(--oc-accent); font-size: 1.3rem; }.oc-scene__tag { display: block; margin-top: 12px; color: var(--oc-accent); font-size: .68rem; font-weight: 750; letter-spacing: .1em; }.oc-scene h3 { margin: 9px 0 7px; font-size: 1.08rem; }.oc-scene p { min-height: 46px; margin: 0; color: var(--vp-c-text-2); font-size: .9rem; line-height: 1.6; }.oc-scene__go { display: block; margin-top: 18px; color: var(--oc-accent); font-size: .8rem; font-weight: 700; }
.oc-capability-list { display: grid; grid-template-columns: repeat(3,1fr); gap: 0; padding: 0; margin: 0; list-style: none; border-top: 1px solid var(--oc-line); border-left: 1px solid var(--oc-line); }.oc-capability-list li { min-width: 0; }.oc-capability-list a { display: grid; grid-template-columns: auto minmax(0,1fr) auto; align-items: center; gap: 12px; min-height: 74px; padding: 16px 18px; border-right: 1px solid var(--oc-line); border-bottom: 1px solid var(--oc-line); color: var(--vp-c-text-1); font-weight: 650; text-decoration: none; transition: background .18s ease; }.oc-capability-list a:hover { background: color-mix(in srgb,var(--oc-accent) 8%,transparent); }.oc-capability-list__icon { color: var(--oc-accent); font-size: 1.05rem; }.oc-capability-list small { color: var(--vp-c-text-2); font-size: .72rem; font-weight: 500; }.oc-capability-list b { color: var(--oc-accent); font-size: .9rem; }
.oc-cta { max-width: 47rem; text-align: center; }.oc-cta .oc-hero__actions { justify-content: center; margin-top: 27px; }.oc-cta .oc-btn--primary { background: var(--oc-accent); color: #fff; }.oc-cta .oc-btn--ghost { border-color: var(--oc-line); color: var(--vp-c-text-1); background: transparent; }
@media (max-width: 920px) { .oc-hero::before { background-position: 58% center; }.oc-hero__layout,.oc-split { grid-template-columns: 1fr; gap: 46px; }.oc-hero__layout { padding: 72px 0; }.oc-workbench { max-width: 650px; transform: none; }.oc-why { grid-template-columns: repeat(2,1fr); }.oc-flow,.oc-capability-list { grid-template-columns: repeat(2,1fr); }.oc-scenes { grid-template-columns: repeat(2,1fr); } }
@media (max-width: 600px) { .oc-hero::before { background: linear-gradient(0deg, rgba(17,19,18,.84), rgba(17,19,18,.70)), url('/hero-cottage-v2.png') 58% center / cover no-repeat; }.oc-wrap { width: min(100% - 32px,1120px); }.oc-hero h1 { font-size: 2.35rem; }.oc-hero h1 span { white-space: normal; }.oc-workflow { padding: 25px; }.oc-why,.oc-flow,.oc-scenes,.oc-capability-list { grid-template-columns: 1fr; }.oc-band { padding: 68px 0; }.oc-scenes { border-right: 1px solid var(--oc-line); }.oc-scene { min-height: 0; }.oc-scene p { min-height: 0; } }
</style>
